In [1]:
import os
import json
from pathlib import Path
import numpy as np
import pandas as pd

pd.set_option('max_colwidth', 80)

In [2]:
# This is where our downloaded images and metadata live locally
DATA_PATH = r'C:\\Users\\mfarj\\Documents\\ss_data\\'

In [3]:
df_full_images = pd.read_csv(DATA_PATH + '\SnapshotSerengeti_v2_1_images.csv')
df_full_annotations = pd.read_csv(DATA_PATH + '\SnapshotSerengeti_v2_1_annotations.csv')

C:\Users\mfarj\AppData\Local\conda\conda\envs\thesisprep\lib\site-packages\IPython\core\interactiveshell.py:3147: DtypeWarning: Columns (8,12) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
df_full_images.columns[0]

'Unnamed: 0'

In [5]:
df_full_images.rename(columns = {'Unnamed: 0':'seq_id'}, inplace=True)

In [6]:
df_full_images.head()

,seq_id,capture_id,image_rank_in_capture,image_path_rel
0,0,SER_S1#B04#1#1,1,S1/B04/B04_R1/S1_B04_R1_PICT0001.JPG
1,1,SER_S1#B04#1#2,1,S1/B04/B04_R1/S1_B04_R1_PICT0002.JPG
2,2,SER_S1#B04#1#3,1,S1/B04/B04_R1/S1_B04_R1_PICT0003.JPG
3,3,SER_S1#B04#1#4,1,S1/B04/B04_R1/S1_B04_R1_PICT0004.JPG
4,4,SER_S1#B04#1#5,1,S1/B04/B04_R1/S1_B04_R1_PICT0005.JPG

In [7]:
df_full_images.shape

(7178440, 4)

In [8]:
df_full_images.index = df_full_images.capture_id

In [9]:
df_full_images.seq_id

capture_id
SER_S1#B04#1#1            0
SER_S1#B04#1#2            1
SER_S1#B04#1#3            2
SER_S1#B04#1#4            3
SER_S1#B04#1#5            4
                      ...
SER_S11#T11#1#129    499396
SER_S11#T11#1#130    499397
SER_S11#T11#1#131    499398
SER_S11#T11#1#131    499399
SER_S11#T11#1#131    499400
Name: seq_id, Length: 7178440, dtype: int64

In [10]:
df_full_annotations.head()

,Unnamed: 0,capture_id,season,site,roll,capture,capture_date_local,capture_time_local,subject_id,question__species,...,question__count_min,question__standing,question__resting,question__moving,question__eating,question__interacting,question__young_present,p_users_identified_this_species,pielous_evenness_index,question__horns_visible
0,0,SER_S1#B04#1#1,S1,B04,1,1,2010-07-18,16:26:14,ASG0002kjh,human,...,1,0.62,0.06,0.0,0.00,0.50,0.0,1.0,0.0,NaN
1,1,SER_S1#B04#1#2,S1,B04,1,2,2010-07-18,16:26:30,ASG0002kji,human,...,1,0.10,0.62,0.0,0.05,0.33,0.0,1.0,0.0,NaN
2,2,SER_S1#B04#1#3,S1,B04,1,3,2010-07-20,06:14:06,ASG0002kjj,blank,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN
3,3,SER_S1#B04#1#4,S1,B04,1,4,2010-07-22,08:56:06,ASG0002kjk,blank,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN
4,4,SER_S1#B04#1#5,S1,B04,1,5,2010-07-24,01:16:28,ASG0002kjl,blank,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN

In [11]:
df_full_annotations.rename(columns = {'Unnamed: 0':'seq_id'}, inplace=True)

In [12]:
df_full_annotations.shape

(2688077, 22)

In [13]:
print('Annotated Sequences: ' + str(df_full_annotations.capture_id.nunique()))
# number of sequences
print('Unique Sequences: ' + str(df_full_images.capture_id.nunique()))

Annotated Sequences: 2659222
Unique Sequences: 2659222

In [14]:
df_full_images['season'] = df_full_images.capture_id.map(lambda x: x.split('#')[0])

In [15]:
df_full_images.season.value_counts().sort_index()

SER_S1     411414
SER_S10    685481
SER_S11    499401
SER_S2     573200
SER_S3     392507
SER_S4     531554
SER_S5     827224
SER_S6     462846
SER_S7     832153
SER_S8     980256
SER_S9     982404
Name: season, dtype: int64

In [16]:
#reduce to first frame only for all sequences. Not doing this now and taking all the images in
#df_full_images = df_full_images.sort_values('file_name').groupby('seq_id').first()

In [17]:
df_full_annotations.head()

,seq_id,capture_id,season,site,roll,capture,capture_date_local,capture_time_local,subject_id,question__species,...,question__count_min,question__standing,question__resting,question__moving,question__eating,question__interacting,question__young_present,p_users_identified_this_species,pielous_evenness_index,question__horns_visible
0,0,SER_S1#B04#1#1,S1,B04,1,1,2010-07-18,16:26:14,ASG0002kjh,human,...,1,0.62,0.06,0.0,0.00,0.50,0.0,1.0,0.0,NaN
1,1,SER_S1#B04#1#2,S1,B04,1,2,2010-07-18,16:26:30,ASG0002kji,human,...,1,0.10,0.62,0.0,0.05,0.33,0.0,1.0,0.0,NaN
2,2,SER_S1#B04#1#3,S1,B04,1,3,2010-07-20,06:14:06,ASG0002kjj,blank,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN
3,3,SER_S1#B04#1#4,S1,B04,1,4,2010-07-22,08:56:06,ASG0002kjk,blank,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN
4,4,SER_S1#B04#1#5,S1,B04,1,5,2010-07-24,01:16:28,ASG0002kjl,blank,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN

In [18]:
df_full_annotations.groupby(['question__species'])['seq_id'].count()

question__species
aardvark          808
aardwolf          456
baboon           3028
bat                 5
batEaredFox       601
                ...
wildcat           103
wilddog             1
wildebeest     197080
zebra          139214
zorilla            45
Name: seq_id, Length: 76, dtype: int64

In [19]:
df_count_specie = df_full_annotations.groupby(['question__species'])['seq_id'].count().reset_index(name='count').sort_values(['count'], ascending=False)

In [20]:
specie_list = [df_count_specie.loc[(df_count_specie['count'] >= 100) & (df_count_specie['count'] <= 500)]['question__species']]

In [21]:
specie_list

[1         aardwolf
 46         leopard
 9         bushbuck
 19            fire
 51        lionmale
 27      guineafowl
 35    hyenaStriped
 44     koribustard
 15          dikdik
 59        reptiles
 10         caracal
 68         vulture
 61         rodents
 71         wildcat
 16          duiker
 Name: question__species, dtype: object]

In [22]:
df_full_images = df_full_images[df_full_images.season.isin(['SER_S11'])]
df_full_annotations = df_full_annotations[df_full_annotations.capture_id.isin(df_full_images.capture_id)]

In [23]:
df_full_images.capture_id.nunique()

188231

In [24]:
df_full_annotations.capture_id.nunique()

188231

In [25]:
ss_data_host = str('https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped')
ss_data_authentication = str('?st=2020-01-01T00%3A00%3A00Z&se=2034-01-01T00%3A00%3A00Z&sp=rl&sv=2019-07-07&sr=c&sig=/DGPd%2B9WGFt6HgkemDFpo2n0M1htEXvTq9WoHlaH7L4%3D')

In [26]:
df_full_images['file_name'] = df_full_images.apply(
    lambda x: (ss_data_host + str(f'/{x.image_path_rel}') + ss_data_authentication), axis=1
)

In [27]:
df_full_images.file_name.head()

capture_id
SER_S11#B03#1#1    https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
SER_S11#B03#1#2    https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
SER_S11#B03#1#3    https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
SER_S11#B03#1#4    https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
SER_S11#B03#1#4    https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
Name: file_name, dtype: object

In [28]:
df_full_annotations.question__species.unique()

array(['blank', 'human', 'zebra', 'elephant', 'buffalo', 'porcupine',
       'jackal', 'warthog', 'baboon', 'giraffe', 'gazellethomsons',
       'impala', 'hyenaspotted', 'hartebeest', 'gazellegrants', 'leopard',
       'cheetah', 'hyenastriped', 'wildebeest', 'topi', 'duiker', 'eland',
       'dikdik', 'hippopotamus', 'fire', 'birdother', 'secretarybird',
       'monkeyvervet', 'ostrich', 'serval', 'aardvark', 'lionfemale',
       'guineafowl', 'hare', 'reedbuck', 'hyenabrown', 'insectspider',
       'lionmale', 'koribustard', 'bat', 'vulture', 'cattle', 'mongoose',
       'wilddog', 'bushbuck', 'wildcat', 'aardwolf', 'genet',
       'batearedfox', 'civet', 'rhinoceros', 'waterbuck', 'kudu',
       'pangolin', 'honeybadger', 'zorilla', 'reptiles', 'lioncub',
       'caracal', 'steenbok', 'rodents'], dtype=object)

In [29]:
from IPython.display import Image 

def look_at_random_animal_from_web(specie, random_state, width=500):
    capture_ids = df_full_annotations.loc[df_full_annotations.question__species == specie].capture_id
    if capture_ids.size == 0:
        return 'No specie matching the description'
    filenames = df_full_images.loc[capture_ids].file_name
    filename = filenames.sample(random_state=random_state).values[0]
    print(filename)
    return Image(url= str(filename), width=500, height=500)

In [30]:
df_full_images.head()

,seq_id,capture_id,image_rank_in_capture,image_path_rel,season,file_name
capture_id,,,,,,
SER_S11#B03#1#1,0,SER_S11#B03#1#1,1,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0001.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
SER_S11#B03#1#2,1,SER_S11#B03#1#2,1,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0002.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
SER_S11#B03#1#3,2,SER_S11#B03#1#3,1,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0003.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
SER_S11#B03#1#4,3,SER_S11#B03#1#4,1,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0004.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
SER_S11#B03#1#4,4,SER_S11#B03#1#4,2,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0005.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...

In [31]:
df_full_images

,seq_id,capture_id,image_rank_in_capture,image_path_rel,season,file_name
capture_id,,,,,,
SER_S11#B03#1#1,0,SER_S11#B03#1#1,1,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0001.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
SER_S11#B03#1#2,1,SER_S11#B03#1#2,1,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0002.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
SER_S11#B03#1#3,2,SER_S11#B03#1#3,1,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0003.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
SER_S11#B03#1#4,3,SER_S11#B03#1#4,1,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0004.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
SER_S11#B03#1#4,4,SER_S11#B03#1#4,2,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0005.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
...,...,...,...,...,...,...
SER_S11#T11#1#129,499396,SER_S11#T11#1#129,1,SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0332.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
SER_S11#T11#1#130,499397,SER_S11#T11#1#130,1,SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0333.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
SER_S11#T11#1#131,499398,SER_S11#T11#1#131,1,SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0334.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
SER_S11#T11#1#131,499399,SER_S11#T11#1#131,2,SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0335.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
SER_S11#T11#1#131,499400,SER_S11#T11#1#131,3,SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0336.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...

In [53]:

base_dir = os.path.join("c:/", "Users", "mfarj", "Documents", "ss_data")
src_dir = os.path.join(base_dir, "per_camera", "snapshotserengeti-unzipped",
                       "snapshotserengeti-unzipped")

df_full_images['file_name_local'] = df_full_images.apply(
    lambda x: (src_dir + '/' + x.image_path_rel), axis=1
)

In [54]:
df_full_images

,seq_id,capture_id,image_rank_in_capture,image_path_rel,season,file_name,file_name_local
capture_id,,,,,,,
SER_S11#B03#1#1,0,SER_S11#B03#1#1,1,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0001.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...
SER_S11#B03#1#2,1,SER_S11#B03#1#2,1,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0002.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...
SER_S11#B03#1#3,2,SER_S11#B03#1#3,1,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0003.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...
SER_S11#B03#1#4,3,SER_S11#B03#1#4,1,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0004.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...
SER_S11#B03#1#4,4,SER_S11#B03#1#4,2,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0005.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...
...,...,...,...,...,...,...,...
SER_S11#T11#1#129,499396,SER_S11#T11#1#129,1,SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0332.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...
SER_S11#T11#1#130,499397,SER_S11#T11#1#130,1,SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0333.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...
SER_S11#T11#1#131,499398,SER_S11#T11#1#131,1,SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0334.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...
SER_S11#T11#1#131,499399,SER_S11#T11#1#131,2,SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0335.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...
SER_S11#T11#1#131,499400,SER_S11#T11#1#131,3,SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0336.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...

In [33]:
look_at_random_animal_from_web(specie='zebra', random_state=234)

https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11/H01/H01_R1/SER_S11_H01_R1_IMAG0606.JPG?st=2020-01-01T00%3A00%3A00Z&se=2034-01-01T00%3A00%3A00Z&sp=rl&sv=2019-07-07&sr=c&sig=/DGPd%2B9WGFt6HgkemDFpo2n0M1htEXvTq9WoHlaH7L4%3D

In [34]:
from PIL import Image

In [35]:
img_file = r'C:\Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snapshotserengeti-unzipped\SER_S11\F04\F04_R1\SER_S11_F04_R1_IMAG0065.JPG'

In [36]:
I = np.asarray(Image.open(img_file))

In [37]:
I.shape

(192, 256, 3)

In [38]:
img_file2 = r'C:\Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snapshotserengeti-unzipped\SER_S11\F04\F04_R1\SER_S11_F04_R1_IMAG0022.JPG'
I2 = np.asarray(Image.open(img_file2))
I2.shape

(192, 256, 3)

In [39]:
df_full_annotations.columns

Index(['seq_id', 'capture_id', 'season', 'site', 'roll', 'capture',
       'capture_date_local', 'capture_time_local', 'subject_id',
       'question__species', 'question__count_max', 'question__count_median',
       'question__count_min', 'question__standing', 'question__resting',
       'question__moving', 'question__eating', 'question__interacting',
       'question__young_present', 'p_users_identified_this_species',
       'pielous_evenness_index', 'question__horns_visible'],
      dtype='object')

In [40]:
df_full_images

,seq_id,capture_id,image_rank_in_capture,image_path_rel,season,file_name,file_name_local
capture_id,,,,,,,
SER_S11#B03#1#1,0,SER_S11#B03#1#1,1,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0001.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,C://SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0001.JPG
SER_S11#B03#1#2,1,SER_S11#B03#1#2,1,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0002.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,C://SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0002.JPG
SER_S11#B03#1#3,2,SER_S11#B03#1#3,1,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0003.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,C://SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0003.JPG
SER_S11#B03#1#4,3,SER_S11#B03#1#4,1,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0004.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,C://SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0004.JPG
SER_S11#B03#1#4,4,SER_S11#B03#1#4,2,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0005.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,C://SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0005.JPG
...,...,...,...,...,...,...,...
SER_S11#T11#1#129,499396,SER_S11#T11#1#129,1,SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0332.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,C://SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0332.JPG
SER_S11#T11#1#130,499397,SER_S11#T11#1#130,1,SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0333.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,C://SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0333.JPG
SER_S11#T11#1#131,499398,SER_S11#T11#1#131,1,SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0334.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,C://SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0334.JPG
SER_S11#T11#1#131,499399,SER_S11#T11#1#131,2,SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0335.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,C://SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0335.JPG
SER_S11#T11#1#131,499400,SER_S11#T11#1#131,3,SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0336.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,C://SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0336.JPG

In [55]:
df_full = df_full_images.join(df_full_annotations.set_index('capture_id'), how='inner', on=None, lsuffix='_x', rsuffix='_y')

In [42]:
df_full_annotations.count

<bound method DataFrame.count of          seq_id         capture_id   season site  roll  capture  \
2497385       0    SER_S11#B03#1#1  SER_S11  B03     1        1
2497386       1    SER_S11#B03#1#2  SER_S11  B03     1        2
2497387       2    SER_S11#B03#1#3  SER_S11  B03     1        3
2497388       3    SER_S11#B03#1#4  SER_S11  B03     1        4
2497389       4    SER_S11#B03#1#5  SER_S11  B03     1        5
...         ...                ...      ...  ...   ...      ...
2688072  190687  SER_S11#T11#1#127  SER_S11  T11     1      127
2688073  190688  SER_S11#T11#1#128  SER_S11  T11     1      128
2688074  190689  SER_S11#T11#1#129  SER_S11  T11     1      129
2688075  190690  SER_S11#T11#1#130  SER_S11  T11     1      130
2688076  190691  SER_S11#T11#1#131  SER_S11  T11     1      131

        capture_date_local capture_time_local subject_id question__species  \
2497385         2015-08-05           10:41:29   18837479             blank
2497386         2015-08-05           10:41:40   18837481             blank
2497387         2015-08-05           10:41:45   18837482             blank
2497388         2015-08-05           10:42:11   18837483             human
2497389         2015-08-05           10:44:02   18837484             blank
...                    ...                ...        ...               ...
2688072         2015-11-17           18:06:12   31711348             blank
2688073         2015-11-17           18:24:16   31711350             blank
2688074         2015-11-17           18:27:05   31711353             blank
2688075         2015-11-17           18:57:53   31711355             blank
2688076         2015-11-18           10:23:36   31711358             human

         ... question__count_min question__standing question__resting  \
2497385  ...                 NaN               0.07              0.00
2497386  ...                 NaN                NaN               NaN
2497387  ...                 NaN                NaN               NaN
2497388  ...                 NaN               0.62              0.00
2497389  ...                 NaN               0.07              0.07
...      ...                 ...                ...               ...
2688072  ...                 NaN                NaN               NaN
2688073  ...                 NaN                NaN               NaN
2688074  ...                 NaN                NaN               NaN
2688075  ...                 NaN                NaN               NaN
2688076  ...                 NaN               0.70              0.00

         question__moving  question__eating  question__interacting  \
2497385              0.07               0.0                   0.00
2497386               NaN               NaN                    NaN
2497387               NaN               NaN                    NaN
2497388              0.38               0.0                   0.23
2497389              0.07               0.0                   0.00
...                   ...               ...                    ...
2688072               NaN               NaN                    NaN
2688073               NaN               NaN                    NaN
2688074               NaN               NaN                    NaN
2688075               NaN               NaN                    NaN
2688076              0.40               0.0                   0.00

         question__young_present  p_users_identified_this_species  \
2497385                      0.0                             0.83
2497386                      NaN                             0.75
2497387                      NaN                             0.75
2497388                      0.0                             1.00
2497389                      0.0                             0.75
...                          ...                              ...
2688072                      NaN                             1.00
2688073                      NaN                             1.00
2688074                      NaN                             1.00
2688075                      NaN                             1.00
2688076                      0.0                             1.00

         pielous_evenness_index  question__horns_visible
2497385                     0.0                      NaN
2497386                     0.0                      NaN
2497387                     0.0                      NaN
2497388                     0.0                      NaN
2497389                     0.0                      NaN
...                         ...                      ...
2688072                     0.0                      NaN
2688073                     0.0                      NaN
2688074                     0.0                      NaN
2688075                     0.0                      NaN
2688076                     0.0                      NaN

[190692 rows x 22 columns]>

In [56]:
df_full.count

<bound method DataFrame.count of                    seq_id_x         capture_id  image_rank_in_capture  \
capture_id
SER_S11#B03#1#1           0    SER_S11#B03#1#1                      1
SER_S11#B03#1#10         13   SER_S11#B03#1#10                      1
SER_S11#B03#1#100       168  SER_S11#B03#1#100                      1
SER_S11#B03#1#100       169  SER_S11#B03#1#100                      2
SER_S11#B03#1#100       170  SER_S11#B03#1#100                      3
...                     ...                ...                    ...
SER_S11#T11#1#98     499344   SER_S11#T11#1#98                      2
SER_S11#T11#1#98     499345   SER_S11#T11#1#98                      3
SER_S11#T11#1#99     499346   SER_S11#T11#1#99                      1
SER_S11#T11#1#99     499347   SER_S11#T11#1#99                      2
SER_S11#T11#1#99     499348   SER_S11#T11#1#99                      3

                                                   image_path_rel season_x  \
capture_id
SER_S11#B03#1#1    SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0001.JPG  SER_S11
SER_S11#B03#1#10   SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0014.JPG  SER_S11
SER_S11#B03#1#100  SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0170.JPG  SER_S11
SER_S11#B03#1#100  SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0171.JPG  SER_S11
SER_S11#B03#1#100  SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0172.JPG  SER_S11
...                                                           ...      ...
SER_S11#T11#1#98   SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0280.JPG  SER_S11
SER_S11#T11#1#98   SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0281.JPG  SER_S11
SER_S11#T11#1#99   SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0282.JPG  SER_S11
SER_S11#T11#1#99   SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0283.JPG  SER_S11
SER_S11#T11#1#99   SER_S11/T11/T11_R1/SER_S11_T11_R1_IMAG0284.JPG  SER_S11

                                                                                         file_name  \
capture_id
SER_S11#B03#1#1    https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
SER_S11#B03#1#10   https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
SER_S11#B03#1#100  https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
SER_S11#B03#1#100  https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
SER_S11#B03#1#100  https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
...                                                                                            ...
SER_S11#T11#1#98   https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
SER_S11#T11#1#98   https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
SER_S11#T11#1#99   https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
SER_S11#T11#1#99   https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...
SER_S11#T11#1#99   https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...

                                                                                   file_name_local  \
capture_id
SER_S11#B03#1#1    c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...
SER_S11#B03#1#10   c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...
SER_S11#B03#1#100  c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...
SER_S11#B03#1#100  c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...
SER_S11#B03#1#100  c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...
...                                                                                            ...
SER_S11#T11#1#98   c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...
SER_S11#T11#1#98   c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...
SER_S11#T11#1#99   c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...
SER_S11#T11#1#99   c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...
SER_S11#T11#1#99   c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...

                   seq_id_y season_y site  ...  question__count_min  \
capture_id                                 ...
SER_S11#B03#1#1           0  SER_S11  B03  ...                  NaN
SER_S11#B03#1#10          9  SER_S11  B03  ...                    1
SER_S11#B03#1#100       100  SER_S11  B03  ...                11-50
SER_S11#B03#1#100       100  SER_S11  B03  ...                11-50
SER_S11#B03#1#100       100  SER_S11  B03  ...                11-50
...                     ...      ...  ...  ...                  ...
SER_S11#T11#1#98     190658  SER_S11  T11  ...                  NaN
SER_S11#T11#1#98     190658  SER_S11  T11  ...                  NaN
SER_S11#T11#1#99     190659  SER_S11  T11  ...                  NaN
SER_S11#T11#1#99     190659  SER_S11  T11  ...                  NaN
SER_S11#T11#1#99     190659  SER_S11  T11  ...                  NaN

                   question__standing question__resting question__moving  \
capture_id
SER_S11#B03#1#1                  0.07              0.00             0.07
SER_S11#B03#1#10                 0.88              0.00             0.12
SER_S11#B03#1#100                0.50              0.08             0.83
SER_S11#B03#1#100                0.50              0.08             0.83
SER_S11#B03#1#100                0.50              0.08             0.83
...                               ...               ...              ...
SER_S11#T11#1#98                  NaN               NaN              NaN
SER_S11#T11#1#98                  NaN               NaN              NaN
SER_S11#T11#1#99                  NaN               NaN              NaN
SER_S11#T11#1#99                  NaN               NaN              NaN
SER_S11#T11#1#99                  NaN               NaN              NaN

                  question__eating question__interacting  \
capture_id
SER_S11#B03#1#1               0.00                  0.00
SER_S11#B03#1#10              0.06                  0.00
SER_S11#B03#1#100             0.75                  0.08
SER_S11#B03#1#100             0.75                  0.08
SER_S11#B03#1#100             0.75                  0.08
...                            ...                   ...
SER_S11#T11#1#98               NaN                   NaN
SER_S11#T11#1#98               NaN                   NaN
SER_S11#T11#1#99               NaN                   NaN
SER_S11#T11#1#99               NaN                   NaN
SER_S11#T11#1#99               NaN                   NaN

                  question__young_present p_users_identified_this_species  \
capture_id
SER_S11#B03#1#1                      0.00                            0.83
SER_S11#B03#1#10                     0.00                            1.00
SER_S11#B03#1#100                    0.25                            1.00
SER_S11#B03#1#100                    0.25                            1.00
SER_S11#B03#1#100                    0.25                            1.00
...                                   ...                             ...
SER_S11#T11#1#98                      NaN                            1.00
SER_S11#T11#1#98                      NaN                            1.00
SER_S11#T11#1#99                      NaN                            1.00
SER_S11#T11#1#99                      NaN                            1.00
SER_S11#T11#1#99                      NaN                            1.00

                  pielous_evenness_index  question__horns_visible
capture_id
SER_S11#B03#1#1                      0.0                      NaN
SER_S11#B03#1#10                     0.0                      NaN
SER_S11#B03#1#100                    0.0                      NaN
SER_S11#B03#1#100                    0.0                      NaN
SER_S11#B03#1#100                    0.0                      NaN
...                                  ...                      ...
SER_S11#T11#1#98                     0.0                      NaN
SER_S11#T11#1#98                     0.0                      NaN
SER_S11#T11#1#99                     0.0                      NaN
SER_S11#T11#1#99                     0.0                      NaN
SER_S11#T11#1#99                     0.0                      NaN

[506455 rows x 28 columns]>

In [44]:
df_full_annotations

,seq_id,capture_id,season,site,roll,capture,capture_date_local,capture_time_local,subject_id,question__species,...,question__count_min,question__standing,question__resting,question__moving,question__eating,question__interacting,question__young_present,p_users_identified_this_species,pielous_evenness_index,question__horns_visible
2497385,0,SER_S11#B03#1#1,SER_S11,B03,1,1,2015-08-05,10:41:29,18837479,blank,...,NaN,0.07,0.00,0.07,0.0,0.00,0.0,0.83,0.0,NaN
2497386,1,SER_S11#B03#1#2,SER_S11,B03,1,2,2015-08-05,10:41:40,18837481,blank,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.75,0.0,NaN
2497387,2,SER_S11#B03#1#3,SER_S11,B03,1,3,2015-08-05,10:41:45,18837482,blank,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.75,0.0,NaN
2497388,3,SER_S11#B03#1#4,SER_S11,B03,1,4,2015-08-05,10:42:11,18837483,human,...,NaN,0.62,0.00,0.38,0.0,0.23,0.0,1.00,0.0,NaN
2497389,4,SER_S11#B03#1#5,SER_S11,B03,1,5,2015-08-05,10:44:02,18837484,blank,...,NaN,0.07,0.07,0.07,0.0,0.00,0.0,0.75,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2688072,190687,SER_S11#T11#1#127,SER_S11,T11,1,127,2015-11-17,18:06:12,31711348,blank,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,0.0,NaN
2688073,190688,SER_S11#T11#1#128,SER_S11,T11,1,128,2015-11-17,18:24:16,31711350,blank,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,0.0,NaN
2688074,190689,SER_S11#T11#1#129,SER_S11,T11,1,129,2015-11-17,18:27:05,31711353,blank,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,0.0,NaN
2688075,190690,SER_S11#T11#1#130,SER_S11,T11,1,130,2015-11-17,18:57:53,31711355,blank,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,0.0,NaN
2688076,190691,SER_S11#T11#1#131,SER_S11,T11,1,131,2015-11-18,10:23:36,31711358,human,...,NaN,0.70,0.00,0.40,0.0,0.00,0.0,1.00,0.0,NaN

In [57]:
df_full.head()

,seq_id_x,capture_id,image_rank_in_capture,image_path_rel,season_x,file_name,file_name_local,seq_id_y,season_y,site,...,question__count_min,question__standing,question__resting,question__moving,question__eating,question__interacting,question__young_present,p_users_identified_this_species,pielous_evenness_index,question__horns_visible
capture_id,,,,,,,,,,,,,,,,,,,,,
SER_S11#B03#1#1,0,SER_S11#B03#1#1,1,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0001.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...,0,SER_S11,B03,...,NaN,0.07,0.00,0.07,0.00,0.00,0.00,0.83,0.0,NaN
SER_S11#B03#1#10,13,SER_S11#B03#1#10,1,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0014.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...,9,SER_S11,B03,...,1,0.88,0.00,0.12,0.06,0.00,0.00,1.00,0.0,NaN
SER_S11#B03#1#100,168,SER_S11#B03#1#100,1,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0170.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...,100,SER_S11,B03,...,11-50,0.50,0.08,0.83,0.75,0.08,0.25,1.00,0.0,NaN
SER_S11#B03#1#100,169,SER_S11#B03#1#100,2,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0171.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...,100,SER_S11,B03,...,11-50,0.50,0.08,0.83,0.75,0.08,0.25,1.00,0.0,NaN
SER_S11#B03#1#100,170,SER_S11#B03#1#100,3,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0172.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...,100,SER_S11,B03,...,11-50,0.50,0.08,0.83,0.75,0.08,0.25,1.00,0.0,NaN

In [58]:
num_species, name_species = pd.factorize(df_full['question__species'])

In [59]:
df_full['encoded_species'] = num_species

In [48]:
file_name = r'C:\\Users\\mfarj\\Documents\\ss_data\\train_csv.csv'
df_full.to_csv(file_name, columns=['image_path_rel','encoded_species'],sep=',',index=False)

In [60]:
df_full.head()
df

,seq_id_x,capture_id,image_rank_in_capture,image_path_rel,season_x,file_name,file_name_local,seq_id_y,season_y,site,...,question__standing,question__resting,question__moving,question__eating,question__interacting,question__young_present,p_users_identified_this_species,pielous_evenness_index,question__horns_visible,encoded_species
capture_id,,,,,,,,,,,,,,,,,,,,,
SER_S11#B03#1#1,0,SER_S11#B03#1#1,1,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0001.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...,0,SER_S11,B03,...,0.07,0.00,0.07,0.00,0.00,0.00,0.83,0.0,NaN,0
SER_S11#B03#1#10,13,SER_S11#B03#1#10,1,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0014.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...,9,SER_S11,B03,...,0.88,0.00,0.12,0.06,0.00,0.00,1.00,0.0,NaN,1
SER_S11#B03#1#100,168,SER_S11#B03#1#100,1,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0170.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...,100,SER_S11,B03,...,0.50,0.08,0.83,0.75,0.08,0.25,1.00,0.0,NaN,1
SER_S11#B03#1#100,169,SER_S11#B03#1#100,2,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0171.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...,100,SER_S11,B03,...,0.50,0.08,0.83,0.75,0.08,0.25,1.00,0.0,NaN,1
SER_S11#B03#1#100,170,SER_S11#B03#1#100,3,SER_S11/B03/B03_R1/SER_S11_B03_R1_IMAG0172.JPG,SER_S11,https://lilablobssc.blob.core.windows.net/snapshotserengeti-unzipped/SER_S11...,c:/Users\mfarj\Documents\ss_data\per_camera\snapshotserengeti-unzipped\snaps...,100,SER_S11,B03,...,0.50,0.08,0.83,0.75,0.08,0.25,1.00,0.0,NaN,1

In [66]:
file_path_rel = []
question_species = []

for index, row in df_full.iterrows():
    if os.path.isfile(row['file_name_local']):
        file_path_rel.append(row['image_path_rel'])
        question_species.append(row['question__species'])

print(len(file_path_rel))
print(len(question_species))

88137
88137

In [ ]:
from pandas import Dat

In [68]:
df_final = pd.DataFrame({'file_path': file_path_rel, 'species': question_species})
num_species, name_species = pd.factorize(df_final['species'])
df_final['encoded_species'] = num_species
file_name = r'C:\\Users\\mfarj\\Documents\\ss_data\\train_csv.csv'
df_final.to_csv(file_name, columns=['file_path','encoded_species'],sep=',',index=False)